/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author vic
 */
public class CLAVE extends javax.swing.JFrame {

    private String txt;

    /**
     * Creates new form CLAVE
     */
    public CLAVE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_512 = new javax.swing.JButton();
        btn_1024 = new javax.swing.JButton();
        btn_2048 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_512.setText("512 ");
        btn_512.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_512ActionPerformed(evt);
            }
        });

        btn_1024.setText("1024");
        btn_1024.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1024ActionPerformed(evt);
            }
        });

        btn_2048.setText("2048");
        btn_2048.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2048ActionPerformed(evt);
            }
        });

        jLabel1.setText("SELECCIONE EL TAMAÑO DE LA CLAVE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_2048)
                            .addComponent(btn_512)
                            .addComponent(btn_1024))
                        .addGap(160, 160, 160))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(btn_512)
                .addGap(35, 35, 35)
                .addComponent(btn_1024)
                .addGap(35, 35, 35)
                .addComponent(btn_2048)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public void setTexto(String txt){
        this.txt = txt;
    }    

    private void btn_512ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_512ActionPerformed
        // TODO add your handling code here:
        CIFRADO wcifrado = new CIFRADO();
        wcifrado.setLLave(512, txt);
        wcifrado.setVisible(true);
        wcifrado.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_512ActionPerformed
    
    private void btn_2048ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2048ActionPerformed
        // TODO add your handling code here:
        CIFRADO wcifrado = new CIFRADO();
        wcifrado.setLLave(2048, txt);
        wcifrado.setVisible(true);
        wcifrado.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_2048ActionPerformed

    private void btn_1024ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1024ActionPerformed
        // TODO add your handling code here:
        CIFRADO wcifrado = new CIFRADO();
        wcifrado.setLLave(1024, txt);
        wcifrado.setVisible(true);
        wcifrado.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_1024ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CLAVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CLAVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CLAVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CLAVE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CLAVE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_1024;
    private javax.swing.JButton btn_2048;
    private javax.swing.JButton btn_512;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
